config/routes.rb
Mantropy::Application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :member do
    resource to: 'home#index'

    resources :books, except: :destroy
    resources :posts, except: :destroy
    resources :ranks
    resources :topics, except: %i[destroy show]
    get '/topics/:id(/((:from)(-:to))(/:top))' => 'topics#show', constraints: { id: /\d+/ }
    resources :wikis, only: %i[index create new]
    resources :users, only: %i[create update edit new]
    resources :site_configs, only: %i[index create update destroy]

    resources :series, only: %i[index new create edit update] do
      scope module: :series do
        resource :author, only: :update
        resource :magazine_serie, only: :update
        resource :post, only: :update
      end
    end

    resources :rankings, only: %i[index show update create]
    resources :magazines, only: %i[index update]
    post '/magazines/merge' => 'magazines#merge', :as => 'magarines_merge'
    # どこからも呼ばれていないので不要？
    # get '/remove_duplications/:ranking_id(/:order_by)' => "series#remove_duplications"
  end

  # 分離済み
  get '/robots' => 'home#robots'

  root to: 'home#index'
  resources :users, only: %i[index show]

  get '/:name/series/:id' => 'series#show', :as => 'serie', :via => :get
  resources :series, only: %i[index]
  get '/series/:id' => 'series#show'
  resources :rankings, only: %i[index] do
    scope module: :rankings do
      resources :series, only: %i[index] do
        get 'aggregated', on: :collection
      end
    end
  end

  get '/wikis/:name' => 'wikis#show', :as => 'wiki'

  devise_for :userauths, controllers: { registrations: 'devise_registrations' }
  devise_scope :userauths do
    get '/userauths/sign_out' => 'devise/sessions#destroy'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = '京大の漫画読みサークル 京大漫トロピー'
    @content = HikiDoc.to_html(Wiki.where(name: 'top').order(created_at: :desc).limit(1)[0]&.content || '')
  end

  def how_to_use
    @title = 'はうとぅゆーず'
  end

  def robots
    respond_to do |format|
      format.text { render plain: '' }
    end
  end
end

app/controllers/member/home_controller.rb
class Member::HomeController < Member::Base
  def index
    @wiki = Wiki.where(name: 'logged_in').order(created_at: :desc).limit(1).first
    @wikis = Wiki.where(name: @wiki&.name).order(created_at: :desc)
  end
end

app/views/home/how_to_use.html.haml
ランキング50位までの作品にコメントを付けていきましょう。はい。
%h1= link_to "全体ランキング", rankings_path
= "ちなみに、レスを返すときは >>3 とかを使って下さい。"
%br
= image_tag "explanation10.png"
%br
こんな感じ。
%hr{:size => "300"}/
%h1= link_to "ランキング", rankings_path
%h1= link_to "個人ランキング", users_path
糞漫画ランキング登録も全体ランキングと同様に行なって下さい。
%em{:stype => "color: red;"} 全体ランキングに載ってない漫画を糞漫画ランキングに登録しないで下さい
%br
= image_tag "explanation0.png"
%hr
= image_tag "explanation1.png"
%hr
= image_tag "explanation2.png"
%hr
= image_tag "explanation3.png"
%hr
= image_tag "explanation4.png"
%hr
= image_tag "explanation5.png"
%hr
%p
  %em{:style => "color: red;"} 雑誌一覧に掲載誌がない！？
  %br
  1. 雑誌名で検索すると、Amazonに扱いがあれば自動的に追加されます
  %br
  2. Amazonに扱いがない場合、Wikipediaを検索してページ名をコピーし、登録時に「右のボックスから雑誌を追加」を選んだ状態で右のボックスに雑誌名を入力して下さい
  %br
%p
  %em{:style => "color: red;"} 検索しても漫画が出てこない
  %br
  1. 受け付けるのは、「半角英数字と全角日本語」のみです。
  %br
  　　
  %a{:href => "/search?utf8=%E2%9C%93&str=%E3%82%A2%E3%83%8A%E3%83%AB%E3%82%A8%E3%83%B3%E3%82%B8%E3%82%A7%E3%83%AB"}> アナルエンジェル
  は正解で
  %a{:href => "/search?utf8=%E2%9C%93&str=%EF%BD%B1%EF%BE%85%EF%BE%99%EF%BD%B4%EF%BE%9D%EF%BD%BC%EF%BE%9E%EF%BD%AA%EF%BE%99&commit=%E6%A4%9C%E7%B4%A2&scope=mantropy"}> ｱﾅﾙｴﾝｼﾞｪﾙ
  は間違い
  %br
  　　
  %a{:href => "/search?utf8=%E2%9C%93&str=%E3%82%A8%E3%83%AA%E3%82%A251"}> エリア51
  は正解で
  %a{:href => "/search?utf8=%E2%9C%93&str=%E3%82%A8%E3%83%AA%E3%82%A2%EF%BC%95%EF%BC%91&commit=%E6%A4%9C%E7%B4%A2&scope=amazon"}> エリア５１
  は間違い
  %br
  2. タイトルに数字の入ってる漫画は狂うことがあるみたいです。数字以前の文字で試してみてください
  %br
%p
  %em{:style => "color: red;"} タイトルで検索しても出てこないかつ、アンソロジーの収録である作品を登録したい
  %br
  1. アンソロジー名で検索します
  %br
  2. 収録のあるアンソロジーをクリックします
  %br
  3. [このシリーズに含まれるシリーズを新しく作る]をクリックします
  %br
  4. [タイトル], [漫画家], [掲載誌], [掲載書籍]を入力・選択し、[Create Serie]をクリック
  %br
  5. 以降、ランキング登録の手順に従って下さい
  %br
%p
  %em{:style => "color: red;"} タイトルで検索しても出てこないかつ、雑誌の読み切りである作品を登録したい
  %br
  1. 雑誌名で検索します
  %br
  2. 収録のある雑誌名をクリックします
  %br
  3. [このシリーズに含まれるシリーズを新しく作る]をクリックします
  %br
  4. [タイトル], [漫画家], [掲載誌], [掲載書籍]を入力・選択し、[Create Serie]をクリック
  %br
  5. 以降、ランキング登録の手順に従って下さい
  %br
  = image_tag "explanation7.png"
  %hr
  = image_tag "explanation8.png"
  %hr
  = image_tag "explanation9.png"
  %hr
%p
  %em{:style => "color: red;"} タイトルまたは掲載された雑誌検索しても出てこない読み切り作品・Web漫画を登録したい
  %br
  1. 何かしらで検索します
  %br
  3. [検索しても出てこない雑誌に掲載された読み切りや・Web漫画などの新しい漫画シリーズを作成する]をクリックします
  %br
  4. [タイトル], [漫画家], [掲載誌]を入力・選択し、[Create Serie]をクリック
  %br
  5. 以降、ランキング登録の手順に従って下さい
  %hr
  = image_tag "explanation6.png"
  %hr

app/views/home/index.html.haml
%div{:align => "center", :style => "background-color: black; padding: 0px; margin: 0px; border: 0px;", :width => "100%"}
  %table#home_index_table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "760"}
    %tr
      %td{:align => "center", :colspan => "2"}
        %marquee{:border => "0", :scrollamount => "3", :scrolldelay => "48"}
          %font{:color => "skyblue"}
            マンガ読みたちが集うサークル、漫トロピーへよおこそ。
            漫トロピーは漫画好きな人たちが集まって漫画の貸し借りをしたり、
            年二回(08年度の場合)漫画についての冊子作成をしたりするサークルです。
            詳細な活動内容は
            %a{:href => wiki_path('about')}> 活動内容
            をご覧ください。
    %tr
      %td{:align => "left", :valign => "top"}
        = image_tag "top.gif", alt: "愛生会病院風漫トロピーロゴ"
      %td{:align => "left", :valign => "top"}
        %table{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "360"}
          %tr
            %td{:colspan => "2"}
              = image_tag "logo.gif", width: "360", alt: "京大漫トロピー"
          %tr
            %td マンガ読みたちが集うサークル、漫トロピーへよおこそ。
            %td
              = image_tag "logo.gif", width: "180", alt: "京大漫トロピー"
          %tr
            %td
              = image_tag "logo.gif", width: "180", alt: "京大漫トロピー"
            %td 漫トロピーは漫画好きな人たちが集まって漫画の貸し借りをしたり、
          %tr
            %td 年二回(08年度の場合)漫画についての冊子作成をしたりするサークルです。
            %td
              = image_tag "logo.gif", width: "180", alt: "京大漫トロピー"
          %tr
            %td
              = image_tag "logo.gif", width: "180", alt: "京大漫トロピー"
            %td
              詳細な活動内容は上メニューより
              %a{:href => wiki_path('about')}> 活動内容
              をご覧ください。
    %tr
      %td{:colspan => "2", :height => "8"}
    %tr
      %td{:align => "left", :colspan => "2", :valign => "top"}
        = raw @content
        %p{:style => "color: black;"}
          キェェェェエエエエ！！！
    %tr
      %td{:align => "center", :background => image_url("mantro_chan.jpg"), :colspan => "2", :height => "302", :valign => "bottom"}
        = image_tag "logo_m.gif"
        %br
        %font{:color => "black"} 漫トロのイメージキャラクター、「まんとろちゃん」