config/routes.rb
Mantropy::Application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :member do
    resource to: 'home#index'

    resources :books, except: :destroy
    resources :posts, except: :destroy
    resources :ranks
    resources :topics, except: %i[destroy show]
    get '/topics/:id(/((:from)(-:to))(/:top))' => 'topics#show', constraints: { id: /\d+/ }
    resources :wikis, only: %i[index create new]
    resources :users, only: %i[create update edit new]
    resources :site_configs, only: %i[index create update destroy]

    resources :series, only: %i[index new create edit update] do
      scope module: :series do
        resource :author, only: :update
        resource :magazine_serie, only: :update
        resource :post, only: :update
      end
    end

    resources :rankings, only: %i[index show update create]
    resources :magazines, only: %i[index update]
    post '/magazines/merge' => 'magazines#merge', :as => 'magarines_merge'
    # どこからも呼ばれていないので不要？
    # get '/remove_duplications/:ranking_id(/:order_by)' => "series#remove_duplications"
  end

  # 分離済み
  get '/robots' => 'home#robots'

  root to: 'home#index'
  resources :users, only: %i[index show]

  get '/:name/series/:id' => 'series#show', :as => 'serie', :via => :get
  resources :series, only: %i[index]
  get '/series/:id' => 'series#show'
  resources :rankings, only: %i[index] do
    scope module: :rankings do
      resources :series, only: %i[index] do
        get 'aggregated', on: :collection
      end
    end
  end

  get '/wikis/:name' => 'wikis#show', :as => 'wiki'

  devise_for :userauths, controllers: { registrations: 'devise_registrations' }
  devise_scope :userauths do
    get '/userauths/sign_out' => 'devise/sessions#destroy'
  end
end

app/controllers/devise_registrations_controller.rb
class DeviseRegistrationsController < Devise::RegistrationsController
  before_action :basic_authentication

  protected

  def after_sign_up_path_for(_resource)
    new_member_user_path
  end

  def basic_authentication
    authenticate_or_request_with_http_basic('登録ページ表示用認証') do |user, password|
      user == ENV['DIGEST_USER'] && password == ENV['DIGEST_PASS']
    end
  end
end

app/views/devise_registrations/edit.html.haml
%h2
  Edit #{resource_name.to_s.humanize}
= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f|
  = render "devise/shared/devise_error_messages"
  %div
    = f.label :email
    %br
    = f.email_field :email
  %div
    = f.label :password
    %i (leave blank if you don't want to change it)
    %br
    = f.password_field :password
  %div
    = f.label :password_confirmation
    %br
    = f.password_field :password_confirmation
  %div
    = f.label :current_password
    %i (we need your current password to confirm your changes)
    %br
    = f.password_field :current_password
  %div= f.submit "Update"
%h3 Cancel my account
%p
  Unhappy? #{link_to "Cancel my account", registration_path(resource_name), :confirm => "Are you sure?", :method => :delete}.
= link_to "Back", :back

app/views/devise_registrations/new.html.haml
%h2 登録
= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
  = render "devise/shared/devise_error_messages"
  %div
    = f.label :email
    %br
    = f.email_field :email
  %div
    = f.label :password
    %br
    = f.password_field :password
  %div
    = f.label :password_confirmation
    %br
    = f.password_field :password_confirmation
  %div= f.submit "登録"
= render :partial => "devise/shared/links"