config/routes.rb
Mantropy::Application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :member do
    resource to: 'home#index'

    resources :books, except: :destroy
    resources :posts, except: :destroy
    resources :ranks
    resources :topics, except: %i[destroy show]
    get '/topics/:id(/((:from)(-:to))(/:top))' => 'topics#show', constraints: { id: /\d+/ }
    resources :wikis, only: %i[index create new]
    resources :users, only: %i[create update edit new]
    resources :site_configs, only: %i[index create update destroy]

    resources :series, only: %i[index new create edit update] do
      scope module: :series do
        resource :author, only: :update
        resource :magazine_serie, only: :update
        resource :post, only: :update
      end
    end

    resources :rankings, only: %i[index show update create]
    resources :magazines, only: %i[index update]
    post '/magazines/merge' => 'magazines#merge', :as => 'magarines_merge'
    # どこからも呼ばれていないので不要？
    # get '/remove_duplications/:ranking_id(/:order_by)' => "series#remove_duplications"
  end

  # 分離済み
  get '/robots' => 'home#robots'

  root to: 'home#index'
  resources :users, only: %i[index show]

  get '/:name/series/:id' => 'series#show', :as => 'serie', :via => :get
  resources :series, only: %i[index]
  get '/series/:id' => 'series#show'
  resources :rankings, only: %i[index] do
    scope module: :rankings do
      resources :series, only: %i[index] do
        get 'aggregated', on: :collection
      end
    end
  end

  get '/wikis/:name' => 'wikis#show', :as => 'wiki'

  devise_for :userauths, controllers: { registrations: 'devise_registrations' }
  devise_scope :userauths do
    get '/userauths/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/serie.rb
class Serie < ApplicationRecord
  validates :name, presence: true
  has_many :ranks # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :authors_series # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :authors, through: :authors_series
  has_and_belongs_to_many :books, optional: true # rubocop:disable Rails/HasAndBelongsToMany
  has_many :magazines_series # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :magazines, through: :magazines_series
  has_and_belongs_to_many :tags, optional: true # rubocop:disable Rails/HasAndBelongsToMany
  belongs_to :post, optional: true
  belongs_to :topic, optional: true
  has_many :posts, through: :topic
  validates :name, presence: true

  attr_accessor :rank_info
end

app/controllers/member/base.rb
class Member::Base < ApplicationController
  before_action :authenticate_userauth!
  before_action :authenticate_user!

  private

  def authenticate_user!
    redirect_to new_member_user_path, notice: 'ユーザー情報を登録してください' if current_user.nil?
  end

  def admin_basic_authentication
    authenticate_or_request_with_http_basic('Development Authentication') do |user, password|
      user == ENV['DIGEST_USER'] && password == ENV['DIGEST_PASS']
    end
  end
end

app/controllers/member/books_controller.rb
class Member::BooksController < Member::Base
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @books = Book.all
  end

  def show; end

  def new
    @book = Book.new
  end

  def edit; end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to(member_book_path(@book), notice: 'Book was successfully created.')
    else
      render action: 'new'
    end
  end

  def update
    if @book.update(book_params)
      redirect_to(member_book_path(@book), notice: 'Book was successfully updated.')
    else
      render action: 'edit'
    end
  end

  def destroy
    @book.destroy

    redirect_to(member_books_path)
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.expect(
      book: %i[isbn
               name
               publisher
               publificationdate
               kind
               detailurl
               smallimgurl
               mediumimgurl
               largeimgurl]
    )
  end
end

app/controllers/member/home_controller.rb
class Member::HomeController < Member::Base
  def index
    @wiki = Wiki.where(name: 'logged_in').order(created_at: :desc).limit(1).first
    @wikis = Wiki.where(name: @wiki&.name).order(created_at: :desc)
  end
end

app/controllers/member/magazines_controller.rb
class Member::MagazinesController < Member::Base
  def index
    @magazines = Magazine.order(:publisher, :name)
  end
end

app/controllers/member/posts_controller.rb
class Member::PostsController < Member::Base
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.topic_id = params[:topic_id]
    topic = @post.topic
    redirect_path = (topic.title ? member_topic_path(topic) : serie_path(Serie.find_by(topic_id: topic.id)))
    begin
      Post.transaction do
        @post.user = current_user
        @post.order = Post.where(topic_id: @post.topic_id).count + 1
        @post.save!
        unless /sage/ =~ params[:post][:email]
          topic.updated_at = Time.zone.now
          topic.save!
        end
      end
      redirect_to(redirect_path, notice: '書き込みに成功しました')
    rescue StandardError
      redirect_to(redirect_path, notice: '何かがおかしい。')
    end
  end

  def update
    if @post.update(post_params)
      redirect_to(member_post_path(@post), notice: 'Post was successfully updated.')
    else
      render action: 'edit'
    end
  end

  def destroy
    @post.destroy

    redirect_to(member_posts_path)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.expect(
      post: %i[name
               email
               order
               content
               topic
               user]
    )
  end
end

app/controllers/member/rankings_controller.rb
class Member::RankingsController < Member::Base
  before_action :admin_basic_authentication
  before_action :set_ranking, only: %i[show update]

  def index
    @rankings = Ranking.order(:name)
    @new_ranking = Ranking.new
  end

  def show; end

  def create
    @ranking = Ranking.new(ranking_params)
    @ranking.save!
    redirect_to member_rankings_path
  end

  def update
    @ranking.update!(ranking_params)
    redirect_to member_rankings_path
  end

  private

  def set_ranking
    @ranking = Ranking.find(params[:id])
  end

  def ranking_params
    params.expect(
      ranking: %i[name
                  is_registerable
                  scope_min
                  scope_max
                  kind]
    )
  end
end

app/controllers/member/ranks_controller.rb
class Member::RanksController < Member::Base
  before_action :set_rank, only: %i[show edit update destroy]

  def index
    @ranks = Rank.all
  end

  def show; end

  def new
    @rank = Rank.new
  end

  def edit; end

  def create # rubocop:disable Metrics/AbcSize,Metrics/MethodLength,Metrics/PerceivedComplexity
    params[:rank][:rank].tr!('０-９', '0-9')
    @rank = Rank.new(rank_params)
    @rank.user_id = current_user.id
    s = Serie.find(@rank.serie_id)

    magazine_name = params[:magazine_name].strip
    if !magazine_name.empty? && Magazine.find_by(name: magazine_name).nil?
      magazine = Magazine.new
      magazine.name = magazine_name
      magazine.publisher = s.books.first && s.books.first.publisher
    else
      magazine = Magazine.find_by(name: magazine_name) || Magazine.find_by(id: params[:magazine_id])
    end
    if magazine
      placed = params[:magazine_placed].strip
      if s.magazines_series.where(magazine_id: magazine.id, placed:).empty?
        ms = MagazinesSerie.new
        ms.magazine = magazine
        ms.placed = placed
        ms.serie = s
        ms.save!
      end
    end

    unless Ranking.find(rank_params[:ranking_id]).is_registerable
      redirect_to(user_path(current_user.name), notice: 'ランキングの変更はできません')
      return
    end

    msg = nil
    unless (r = Rank.where(user_id: current_user.id, rank: rank_params[:rank],
                           ranking_id: rank_params[:ranking_id])).empty?
      msg = '上書きしました。'
      @rank = r[0]
      @rank.serie_id = rank_params[:serie_id]
    end
    Rails.logger.debug @rank

    if @rank.save
      redirect_to(user_path(current_user.name),
                  notice: "#{@rank.serie.name} に #{@rank.rank} 位を#{msg || '登録しました。'}")
    else
      redirect_to(@rank.serie, notice: '失敗。ランク登録に合わない情報が混じった気がする')
    end
  end

  def update
    if @rank.update(rank_params)
      redirect_to(member_rank_path(@rank), notice: 'Rank was successfully updated.')
    else
      render action: 'edit'
    end
  end

  def destroy
    if @rank.user_id == current_user.id && @rank.ranking.is_registerable
      @rank.destroy
      redirect_to(user_path(current_user.name))
    else
      redirect_to user_path(@rank.user.name), alert: 'あなたはこのランキングデータのユーザーでないか、またはこのランキングデータは修正できないものです'
    end
  end

  private

  def set_rank
    @rank = Rank.find(params[:id])
  end

  def rank_params
    params.expect(
      rank: %i[rank
               score
               ranking_id
               serie_id]
    )
  end
end

app/controllers/member/series/authors_controller.rb
class Member::Series::AuthorsController < Member::Series::Base
  def update
    case params[:mode]
    when 'remove'
      @serie.authors_series.where(author_id: params[:author_id]).destroy_all
    when 'add'
      aa = Aaaws.normalize_author(params[:author_name])
      a = Author.find_by(name: aa)
      unless a
        a = Author.new
        a.name = aa
        a.save!
      end
      @serie.authors << a
    end
    redirect_to serie_path(@serie)
  end
end

app/controllers/member/series/base.rb
class Member::Series::Base < Member::Base
  before_action :set_serie

  private

  def set_serie
    @serie = Serie.find(params[:serie_id])
  end
end

app/controllers/member/series/magazine_series_controller.rb
class Member::Series::MagazineSeriesController < Member::Series::Base
  def update # rubocop:disable Metrics/AbcSize
    case params[:mode]
    when 'remove'
      @serie.magazines_series.delete(MagazinesSerie.find(params[:magazines_serie_id]))
    when 'add'
      magazine_name = params[:magazine_name].strip
      if !magazine_name.empty? && Magazine.find_by(name: magazine_name).nil?
        magazine = Magazine.new
        magazine.name = magazine_name
        magazine.publisher = @serie.books.first && @serie.books.first.publisher
      else
        magazine = Magazine.find_by(name: magazine_name) || Magazine.find_by(id: params[:magazine_id])
      end
      placed = params[:magazine_placed].strip
      if @serie.magazines_series.where(magazine_id: magazine.id, placed:).empty?
        ms = MagazinesSerie.new
        ms.magazine = magazine
        ms.placed = placed
        ms.serie = @serie
        ms.save!
      end
    end
    redirect_to edit_member_serie_path(@serie)
  end
end

app/controllers/member/series/posts_controller.rb
class Member::Series::PostsController < Member::Series::Base
  def update
    Post.transaction do
      post = Post.new(post_params)
      post.topic_id = params[:topic_id]
      post.user = current_user
      post.order = Post.where(topic_id: post.topic_id).count + 1
      post.save!
      unless /sage/ =~ params[:post][:email]
        @serie.topic.updated_at = Time.zone.now
        @serie.topic.save!
      end
      @serie.post = post
      @serie.save!
    end

    redirect_to serie_path(@serie)
  end

  private

  def post_params
    params.expect(
      post: %i[email
               content]
    )
  end
end

app/controllers/member/series_controller.rb
class Member::SeriesController < Member::Base
  before_action :set_serie, only: %i[edit update destroy]

  @title = 'シリーズ'

  def index
    @title = 'シリーズ一覧'
    @series = Serie.order(id: :desc).page(params[:page])
  end

  def new
    @serie = (params[:id] ? Serie.find(params[:id]) : Serie.new)
    @serie_new = params[:id] || true
  end

  def edit
    @rankings = Ranking.where(is_registerable: true)
  end

  def create # rubocop:disable Metrics/AbcSize
    @serie = Serie.new(serie_params)

    a = Author.find_by(id: params[:author_id]) || Author.find_by(name: params[:author_name].strip)
    unless a
      a = Author.new
      a.name = params[:author_name].strip
      a.save!
    end
    @serie.authors << a

    m = Magazine.find_by(id: params[:magazine_id]) || Magazine.find_by(name: params[:magazine_name].strip)
    unless m
      m = Magazine.new
      m.name = params[:magazine_name].strip
      m.publisher = params[:magazine_publisher].strip
      m.save!
    end
    @serie.magazines << m if m

    params[:book_ids]&.each do |bid|
      @serie.books << Book.find(bid)
    end

    if @serie.save
      redirect_to(serie_path(@serie), notice: 'Serie was successfully created.')
    else
      render action: 'new'
    end
  end

  def update
    if @serie.update(serie_params)
      redirect_to(@serie, notice: 'Serie was successfully updated.')
    else
      render action: 'edit'
    end
  end

  def destroy
    @serie.destroy

    redirect_to(series_url)
  end

  # 不要疑惑
  def remove_duplications
    order_by = params[:order_by]&.gsub('_', '.') || 'authors.name'
    @series = Serie.select(
      'DISTINCT series.*'
    ).includes(
      :ranks, :authors
    ).where(
      ranks: { ranking_id: params[:ranking_id] }
    ).order(
      order_by
    ).page(
      params[:page]
    ).per(1000)
  end

  private

  def set_serie
    @serie = Serie.find(params[:id])
  end

  def serie_params
    params.expect(
      serie: %i[author_name
                magazine_name
                name]
    )
  end
end

app/controllers/member/site_configs_controller.rb
class Member::SiteConfigsController < Member::Base
  before_action :admin_basic_authentication
  before_action :set_site_config, only: %i[update destroy]

  def index
    @site_configs = SiteConfig.order(:path)
  end

  def create
    @site_config = SiteConfig.new(site_config_params)
    @site_config.save!
    redirect_to member_site_configs_path, notice: '当該の設定が追加されました'
  end

  def update
    @site_config.update!(site_config_params)
    redirect_to member_site_configs_path, notice: '当該の設定が変更されました'
  end

  def destroy
    @site_config.destroy!
    redirect_to member_site_configs_path, notice: '当該の設定は削除されました'
  end

  private

  def set_site_config
    @site_config = SiteConfig.find(params[:id])
  end

  def site_config_params
    params.expect(site_config: %i[path name value])
  end
end

app/controllers/member/topics_controller.rb
class Member::TopicsController < Member::Base
  before_action :set_topic, only: %i[show edit update destroy]

  def index
    @topics = Topic.where(appear: 1).order(updated_at: :desc, id: :desc)
  end

  def show
    redirect_to serie_path(Serie.find_by(topic_id: @topic.id)) if @topic.title.nil?
  end

  def new
    @topic = Topic.new
  end

  def edit; end

  def create
    post = Post.new
    begin
      Topic.transaction do
        @topic = Topic.new(topic_params)
        @topic.appear = 1
        raise if @topic.title == '' || @topic.title.nil?

        @topic.save!

        post = Post.new
        post.content = params[:content]
        post.email = params[:email]
        post.user = current_user
        post.order = 1
        post.topic = @topic
        post.save!
      end
      redirect_to(member_topics_path, notice: 'スレッド作成と書き込みに成功しました。')
    rescue StandardError
      redirect_to(member_topics_path, alert: '何かおかしいで。')
    end
  end

  def update
    if @topic.update(topic_params)
      redirect_to(member_topic_path(@topic), notice: 'Topic was successfully updated.')
    else
      render action: 'edit'
    end
  end

  def destroy
    @topic.destroy

    redirect_to(member_topics_path)
  end

  private

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.expect(
      topic: %i[appear
                title]
    )
  end
end

app/helpers/series_helper.rb
module SeriesHelper
  def serie_image_path(serie, size = :medium)
    rtn = nil

    serie.books.each do |book|
      rtn = book.smallimgurl if size == :small
      rtn = book.mediumimgurl if size == :medium
      rtn = book.largeimgurl if size == :large
      break if rtn
    end
    unless rtn
      rtn = 'nil_small.jpg' if size == :small
      rtn = 'nil_medium.jpg' if size == :medium
      rtn = 'nil_large.jpg' if size == :large
    end

    rtn
  end
end

app/views/member/series/_form.html.haml
= form_for([:member, (@serie_new ? Serie.new : @serie)]) do |f|
  - if @serie.errors.any?
    #error_explanation
      %h2
        = pluralize(@serie.errors.count, "error")
        prohibited this series from being saved:
      %ul
        - @serie.errors.full_messages.each do |msg|
          %li= msg
  %div
    Tips シリーズ情報とは？
    %br
    シリース情報とは、ランキングに入れることの出来る漫画の要素という抽象的な概念です。
    %br
    「HUNTER×HUNTER」なら単行本を集約したモノ
    %br
    「金魚王国の崩壊」ならWebサイトに掲載された漫画を集約したモノ
    %br
    「女装少年アンソロジー」なら、「女装少年アンソロジー」というアンソロジー形式それ自体
    %br
    「ミックス＊リリィズ」なら、「女装少年アンソロジー」に掲載された漫画
    %br
    を指します
    %br
  .field
    = f.label "シリーズ名・タイトル"
    %br
    = f.text_field :name, required: true
  .field
    = f.label "著者・漫画家"
    %br
    = select_tag :author_id, options_from_collection_for_select(Author.order("name"), :id, :name, (@serie.authors.empty? ? nil : @serie.authors.last.id)), {:include_blank => "右のボックスから漫画家を追加"}
    = text_field_tag :author_name
  .field
    = f.label "掲載誌"
    %br
    = select_tag :magazine_id, options_from_collection_for_select(Magazine.order("name"), :id, :name, (@serie.magazines.empty? ? nil : @serie.magazines.last.id)), {:include_blank => "右のボックスから雑誌を追加"}
    = text_field_tag :magazine_name
    雑誌出版社:#{text_field_tag :magazine_publisher}
  .field
    = f.label "次の書籍情報を含める"
    %br
    = select_tag :book_ids, options_from_collection_for_select(@serie.books, :id, :name),{:multiple => true}
    CtrlかShiftキーを押下しながらで複数選択(Editing Serieの時は関係ないです)
  .actions
    = hidden_field_tag :serie_id, @serie.id
    = f.submit

app/views/member/series/edit.html.haml
.serie_image
  = image_tag(serie_image_path(@serie, :large), :alt => @serie.name)
.serie_detail
  %h1
    = @serie.name
  %h2 シリーズ情報修正
  %p.serie_authors
    = form_for(@serie) do |f|
      %b タイトル:
      = f.text_field :name
      = f.submit "変更"
  %p.serie_authors
    %h3 著者:
    - if @serie.authors
      - @serie.authors.each do |a|
        = form_tag member_serie_author_path(@serie), :method => :patch, remote: false do
          = a.name
          = hidden_field_tag :mode, :remove
          = hidden_field_tag :author_id, a.id
          = submit_tag "取り除く", :confirm => "#{a.name} を #{@serie.name} から取り除いてよろしいですか？"
    = form_tag member_serie_author_path(@serie), :method => :patch, remote: false do
      = hidden_field_tag :mode, "add"
      = text_field_tag :author_name
      = submit_tag "追加する"
  %p.serie_magazines
    %h3 掲載誌:
    %dl
      %dt 現在の掲載誌情報
      %dd
        %table
          %tr
            %th 雑誌名
            %th 雑誌掲載情報
            %th 出版社
            %th 操作
          - @serie.magazines_series.each do |ms|
            %tr
              = form_tag member_serie_magazine_serie_path(@serie), :method => :patch, remote: false do
                %td= ms.magazine && ms.magazine.name
                %td= ms.placed
                %td= ms.magazine && ms.magazine.publisher
                = hidden_field_tag :mode, :remove
                = hidden_field_tag :magazines_serie_id, ms.id
                %td= submit_tag "取り除く", :confirm => "#{ms.magazine && ms.magazine.name}, #{ms.placed}を #{@serie.name} から取り除いてよろしいですか？"
      %dt 掲載誌情報の追加
      %dd
        %dl
          = form_tag member_serie_magazine_serie_path(@serie), :method => :patch, remote: false do
            = hidden_field_tag :mode, :add
            %dt 雑誌名
            %dd
              = select_tag :magazine_id, options_from_collection_for_select(Magazine.order("name"), :id, :name, (@serie.magazines.empty? ? nil : @serie.magazines.last.id)), {:include_blank => "右のボックスから雑誌を追加"}
              もしくは
              = text_field_tag :magazine_name
            %dt 雑誌掲載情報（読み切りの場合は掲載号、Web漫画はURL、など）
            %dd= text_field_tag :magazine_placed
            %dt 操作
            %dd= submit_tag "追加する"
  %p.serie_post
    %h3 細部:
    = form_tag member_serie_post_path(@serie), :method => :patch, remote: false do
      %dt
        = hidden_field_tag "topic_id", @serie.topic_id
        = submit_tag "書き込み"
        E-mail： #{text_field_tag "post[email]"}
      %dd
        = text_area_tag "post[content]", nil, {:rows => 5, :cols => 64}
%hr
= link_to 'Show', @serie
|
\#{link_to 'Back', series_path}
%p.serie_ranks
  %h2 ランキング登録
  = form_for([:member, Rank.new]) do |f|
    %dl
      %dt 掲載誌
      %dd
        雑誌を選ぶ
        = select_tag :magazine_id, options_from_collection_for_select(Magazine.order("name"), :id, :name, (@serie.magazines.empty? ? nil : @serie.magazines.last.id)), {:include_blank => "右のボックスから雑誌を追加"}
        もしくは
        = text_field_tag :magazine_name
      %dt 雑誌掲載情報（読み切りの場合は掲載号、Web漫画はURL、など）
      %dd= text_field_tag :magazine_placed
      %dt ランキング
      %dd
        順位
        = f.text_field :rank, {:size => 2, :maxlength => 2}
        ※個人ランキングは1~30位、クソランキングは1~5位です
      = f.hidden_field :serie_id, :value => @serie.id
      %dd
        どのランキング
        = f.collection_select :ranking_id, @rankings, :id, :name, {:selected => @rankings.map{|r| complete_ranking(r) ? nil : r.id}.compact.min}
      %dt= f.submit "登録", :confirm => "ランキング登録してよろしいですか？"
  %p
    %em{:style => "color: red;"} 雑誌一覧に掲載誌がない！？
    = succeed "1." do
      %br
    雑誌名で検索して下さい。検索すると、Amazonに扱いがあれば自動的に追加されます
    %br
    2. Amazonに扱いがない場合、
    %a{:href => "http://ja.wikipedia.org/", :target => "_blank"} Wikipedia
    を検索してページ名をコピーし、登録時に「右のボックスから雑誌を追加」を選んだ状態で右のボックスに雑誌名を入力して下さい
= link_to "このシリーズに含まれるシリーズを新しく作る", new_member_serie_path(@serie)

app/views/member/series/index.html.haml
%h1= @title
%table.table
  %thead.table-light
    %tr
      %th ID
      %th 名前
      %th
  %tbody
    - @series.each do |serie|
      %tr
        %td= serie.id
        %td= link_to serie.name, serie_path(serie)
        %td= link_to '編集', edit_member_serie_path(serie), class: 'btn btn-sm btn-outline-secondary'
= paginate @series
%br
= link_to 'シリーズを追加', new_member_serie_path, class: 'btn btn-primary'

app/views/member/series/new.html.haml
%h1 シリーズを追加
= render 'form'
= link_to 'Back', series_path

app/views/member/series/remove_duplications.html.haml
%table
  - @series.each do |serie|
    %tr
      %td
        id:
        = serie.id
      %td= link_to image_tag(serie_image_path(serie, :small), :alt=> serie.name, :style => "float: left;"), serie, {:target => "_blank"}
      %td= link_to serie.name, serie, {:target => "_blank"}
      %td
        - if serie.authors
          - serie.authors.each do |author|
            = link_to author.name, series_path(:str => author.name)
            %br
      %td
        - serie.ranks(:ranking_id => 5).each do |rank|
          = link_to rank.user.name, user_path(rank.user.name) if rank.user
          = rank.rank
          位
          %br
      %td
        ここに統合ボタン