config/routes.rb
Mantropy::Application.routes.draw do # rubocop:disable Metrics/BlockLength
  namespace :member do
    resource to: 'home#index'

    resources :books, except: :destroy
    resources :posts, except: :destroy
    resources :ranks
    resources :topics, except: %i[destroy show]
    get '/topics/:id(/((:from)(-:to))(/:top))' => 'topics#show', constraints: { id: /\d+/ }
    resources :wikis, only: %i[index create new]
    resources :users, only: %i[create update edit new]
    resources :site_configs, only: %i[index create update destroy]

    resources :series, only: %i[index new create edit update] do
      scope module: :series do
        resource :author, only: :update
        resource :magazine_serie, only: :update
        resource :post, only: :update
      end
    end

    resources :rankings, only: %i[index show update create]
    resources :magazines, only: %i[index update]
    post '/magazines/merge' => 'magazines#merge', :as => 'magarines_merge'
    # どこからも呼ばれていないので不要？
    # get '/remove_duplications/:ranking_id(/:order_by)' => "series#remove_duplications"
  end

  # 分離済み
  get '/robots' => 'home#robots'

  root to: 'home#index'
  resources :users, only: %i[index show]

  get '/:name/series/:id' => 'series#show', :as => 'serie', :via => :get
  resources :series, only: %i[index]
  get '/series/:id' => 'series#show'
  resources :rankings, only: %i[index] do
    scope module: :rankings do
      resources :series, only: %i[index] do
        get 'aggregated', on: :collection
      end
    end
  end

  get '/wikis/:name' => 'wikis#show', :as => 'wiki'

  devise_for :userauths, controllers: { registrations: 'devise_registrations' }
  devise_scope :userauths do
    get '/userauths/sign_out' => 'devise/sessions#destroy'
  end
end

app/controllers/member/series/authors_controller.rb
class Member::Series::AuthorsController < Member::Series::Base
  def update
    case params[:mode]
    when 'remove'
      @serie.authors_series.where(author_id: params[:author_id]).destroy_all
    when 'add'
      aa = Aaaws.normalize_author(params[:author_name])
      a = Author.find_by(name: aa)
      unless a
        a = Author.new
        a.name = aa
        a.save!
      end
      @serie.authors << a
    end
    redirect_to serie_path(@serie)
  end
end

app/controllers/member/series/base.rb
class Member::Series::Base < Member::Base
  before_action :set_serie

  private

  def set_serie
    @serie = Serie.find(params[:serie_id])
  end
end

app/controllers/member/series/magazine_series_controller.rb
class Member::Series::MagazineSeriesController < Member::Series::Base
  def update # rubocop:disable Metrics/AbcSize
    case params[:mode]
    when 'remove'
      @serie.magazines_series.delete(MagazinesSerie.find(params[:magazines_serie_id]))
    when 'add'
      magazine_name = params[:magazine_name].strip
      if !magazine_name.empty? && Magazine.find_by(name: magazine_name).nil?
        magazine = Magazine.new
        magazine.name = magazine_name
        magazine.publisher = @serie.books.first && @serie.books.first.publisher
      else
        magazine = Magazine.find_by(name: magazine_name) || Magazine.find_by(id: params[:magazine_id])
      end
      placed = params[:magazine_placed].strip
      if @serie.magazines_series.where(magazine_id: magazine.id, placed:).empty?
        ms = MagazinesSerie.new
        ms.magazine = magazine
        ms.placed = placed
        ms.serie = @serie
        ms.save!
      end
    end
    redirect_to edit_member_serie_path(@serie)
  end
end

app/controllers/member/series/posts_controller.rb
class Member::Series::PostsController < Member::Series::Base
  def update
    Post.transaction do
      post = Post.new(post_params)
      post.topic_id = params[:topic_id]
      post.user = current_user
      post.order = Post.where(topic_id: post.topic_id).count + 1
      post.save!
      unless /sage/ =~ params[:post][:email]
        @serie.topic.updated_at = Time.zone.now
        @serie.topic.save!
      end
      @serie.post = post
      @serie.save!
    end

    redirect_to serie_path(@serie)
  end

  private

  def post_params
    params.expect(
      post: %i[email
               content]
    )
  end
end

app/controllers/member/series_controller.rb
class Member::SeriesController < Member::Base
  before_action :set_serie, only: %i[edit update destroy]

  @title = 'シリーズ'

  def index
    @title = 'シリーズ一覧'
    @series = Serie.order(id: :desc).page(params[:page])
  end

  def new
    @serie = (params[:id] ? Serie.find(params[:id]) : Serie.new)
    @serie_new = params[:id] || true
  end

  def edit
    @rankings = Ranking.where(is_registerable: true)
  end

  def create # rubocop:disable Metrics/AbcSize
    @serie = Serie.new(serie_params)

    a = Author.find_by(id: params[:author_id]) || Author.find_by(name: params[:author_name].strip)
    unless a
      a = Author.new
      a.name = params[:author_name].strip
      a.save!
    end
    @serie.authors << a

    m = Magazine.find_by(id: params[:magazine_id]) || Magazine.find_by(name: params[:magazine_name].strip)
    unless m
      m = Magazine.new
      m.name = params[:magazine_name].strip
      m.publisher = params[:magazine_publisher].strip
      m.save!
    end
    @serie.magazines << m if m

    params[:book_ids]&.each do |bid|
      @serie.books << Book.find(bid)
    end

    if @serie.save
      redirect_to(serie_path(@serie), notice: 'Serie was successfully created.')
    else
      render action: 'new'
    end
  end

  def update
    if @serie.update(serie_params)
      redirect_to(@serie, notice: 'Serie was successfully updated.')
    else
      render action: 'edit'
    end
  end

  def destroy
    @serie.destroy

    redirect_to(series_url)
  end

  # 不要疑惑
  def remove_duplications
    order_by = params[:order_by]&.gsub('_', '.') || 'authors.name'
    @series = Serie.select(
      'DISTINCT series.*'
    ).includes(
      :ranks, :authors
    ).where(
      ranks: { ranking_id: params[:ranking_id] }
    ).order(
      order_by
    ).page(
      params[:page]
    ).per(1000)
  end

  private

  def set_serie
    @serie = Serie.find(params[:id])
  end

  def serie_params
    params.expect(
      serie: %i[author_name
                magazine_name
                name]
    )
  end
end

app/controllers/rankings/series_controller.rb
class Rankings::SeriesController < Rankings::Base
  def index # rubocop:disable Metrics/AbcSize,Metrics/CyclomaticComplexity,Metrics/MethodLength,Metrics/PerceivedComplexity
    @title = '全体ランキング'

    ranking_plus = ranking_minus = nil
    case @ranking.kind
    when 'kojin'
      ranking_plus = @ranking
      ranking_minus = Ranking.where(['name LIKE ? AND kind = ?', "#{@ranking.name[0...4]}%", 'kuso']).last
    when 'kuso'
      ranking_plus = Ranking.where(['name LIKE ? AND kind = ?', "#{@ranking.name[0...4]}%", 'kojin']).last
      ranking_minus = @ranking
    else
      return redirect_to(aggregated_ranking_series_path(@ranking.name))
    end

    share_with = SiteConfig.config('ranking_now_share_with')
    return redirect_to(rankings_path, notice: 'ランキングは集計中なので誰も見れないよ') if share_with == 'no_one'
    if share_with == 'members' && current_user.blank?
      return redirect_to(rankings_path, notice: 'ランキングは集計中なのでメンバーだけが見れるよ')
    end

    # rubocop:disable Layout/LineLength
    sql = 'SELECT s.id, s.name, s.topic_id, s.post_id, ' \
          "'合計得点: '||rs.mark||'　糞補正後得点: '||(rs.mark + COALESCE(rk.mark,0))||'　重複数: '||(COALESCE(rs.count,0))||'　糞重複数: '||(COALESCE(rk.count, 0))||'　コメント数: '||COALESCE(pc.countp, 0)||'　最高順位: '||rs.min_rank AS url, " \
          '(rs.mark + COALESCE(rk.mark,0)) AS amark ' \
          'FROM series s ' \
          'INNER JOIN (' \
          "SELECT (SUM(#{ranking_plus.scope_max + 1} - rank) + ((COUNT(*) - 1) * 3)) AS mark, serie_id, count(id) AS count, MIN(rank) AS min_rank FROM ranks WHERE ranking_id=#{ranking_plus.id} GROUP BY serie_id" \
          ') rs ON s.id=rs.serie_id ' \
          'LEFT JOIN (' \
          "SELECT (SUM(rank - #{ranking_minus.scope_max + 1}) * 2 + (COUNT(*) -1) * (-3)) AS mark, serie_id, count(id) AS count FROM ranks WHERE ranking_id=#{ranking_minus.id} GROUP BY serie_id" \
          ') rk ON s.id = rk.serie_id ' \
          'LEFT JOIN (' \
          "SELECT COUNT(p.id) AS countp, p.topic_id FROM posts p WHERE p.created_at > (SELECT created_at FROM rankings WHERE id=#{ranking_plus.id}) GROUP BY p.topic_id" \
          ') pc ON s.topic_id=pc.topic_id'
    # rubocop:enable Layout/LineLength
    if @ranking == ranking_plus
      sql += ' order by rs.mark DESC, rs.count DESC, rs.min_rank, rk.count'
    elsif @ranking == ranking_minus
      sql += ' order by amark DESC, rs.count DESC, rs.min_rank, rk.count'
    end

    @ranking_ids = [ranking_plus.id, ranking_minus.id]
    @series = Serie.find_by_sql(sql)
    @series.map! do |serie|
      if /^合計得点:\s(\d+)　糞補正後得点:\s(-?\d+)　重複数:\s(\d+)　糞重複数:\s(\d+)　コメント数:\s(\d+)　最高順位:\s(\d+)$/ =~ serie.url
        serie.rank_info = {
          sum_of_mark: Regexp.last_match(1), sum_of_mark_with_kuso: Regexp.last_match(2),
          count_rank: Regexp.last_match(3), count_kuso: Regexp.last_match(4),
          count_post: Regexp.last_match(5), min_rank: Regexp.last_match(6)
        }
      end
      serie
    end
    if @ranking == ranking_plus
      rank = rank_ = sum_of_mark = count_rank = min_rank = 0
      @series.map! do |serie|
        rank_ += 1
        same = serie.rank_info[:sum_of_mark] == sum_of_mark &&
               serie.rank_info[:count_rank] == count_rank &&
               serie.rank_info[:min_rank] == min_rank
        rank = rank_ unless same
        sum_of_mark = serie.rank_info[:sum_of_mark]
        count_rank = serie.rank_info[:count_rank]
        min_rank = serie.rank_info[:min_rank]
        serie.rank_info[:rank] = rank
        serie
      end
    elsif @ranking == ranking_minus
      rank = rank_ = sum_of_mark_with_kuso = count_kuso = min_rank = 0
      @series.map! do |serie|
        rank_ += 1
        same = serie.rank_info[:sum_of_mark_with_kuso] == sum_of_mark_with_kuso &&
               serie.rank_info[:count_kuso] == count_kuso &&
               serie.rank_info[:min_rank] == min_rank
        rank = rank_ unless same
        sum_of_mark_with_kuso = serie.rank_info[:sum_of_mark_with_kuso]
        count_kuso = serie.rank_info[:count_kuso]
        min_rank = serie.rank_info[:min_rank]
        serie.rank_info[:rank] = rank
        serie
      end
    end
    @is_should_comment_term = !ranking_plus.is_registerable && !ranking_minus.is_registerable

    @series = Kaminari.paginate_array(@series).page(params[:page]).per(64)

    respond_to do |format|
      format.html # { render html: (@series = Kaminari.paginate_array(@series).page(params[:page]).per(64)) }
      format.csv #  { render :content_type => 'text/csv' }
      format.xml  { @series = @series[0..55] }
      format.json { @series = @series[0..55] }
    end
  end

  def aggregated
    @title = '全体ランキング'
    sql = 'SELECT s.* FROM series s INNER JOIN ranks r ON s.id=r.serie_id ' \
          "WHERE r.ranking_id=#{@ranking.id} ORDER BY r.rank"
    @series = Kaminari.paginate_array(Serie.find_by_sql(sql)).page(params[:page])
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  @title = 'シリーズ'

  def index # rubocop:disable Metrics/AbcSize,Metrics/MethodLength,Metrics/PerceivedComplexity
    @str = params[:str]
    @title = "#{@str} の検索結果"
    if @str.blank?
      redirect_to root_path, notice: '検索ワードを指定してください'
      return
    end

    if params[:scope] =~ /^rakuten/ && current_user
      begin
        RakutenSearchService.search_and_store(@str)
      rescue StandardError => e
        flash.now[:alert] = e
        raise e if Rails.env.development?
      end
    end

    # サーチワードを空白で分割してor検索
    search_strs = @str.strip.split(/[\s　]/).compact_blank

    # シリーズで名前検索
    series = Serie.none
    search_strs.each.with_index do |s, i|
      series = if i.zero?
                 Serie.where('name LIKE ?', "%#{s}%")
               else
                 series.or(series.where('name_kana LIKE ?', "%#{s}%"))
               end
    end

    # 著者で名前検索
    authors = Author.none
    search_strs.each.with_index do |s, i|
      authors = if i.zero?
                  Author.where('name LIKE ?', "%#{s}%")
                else
                  authors.or(series.where('name_kana LIKE ?', "%#{s}%"))
                end
    end

    # 著者名で引っかかるときはその著者の持っているシリーズを含める
    if authors.exists?
      serie_ids = AuthorsSerie.where(author_id: authors.pluck(:id)).pluck(:serie_id)
      series = series.or(Serie.where(id: serie_ids))
    end

    # ページネーション
    @series = series.page(params[:page]).order(id: :desc)

    if @series.one?
      # 結果が1件の場合はそのシリーズの詳細ページにリダイレクト
      redirect_to serie_path(@series[0])
    else
      render 'index'
    end
  end

  def show
    @serie = Serie.find(params[:id])
    @title = "#{@serie.name} のシリーズ情報"
    # rubocop:disable Layout/LineLength
    # @similar_series = Serie.find_by_sql("SELECT s.* FROM series s INNER JOIN (SELECT r1.serie_id, COUNT(*) AS similarity FROM ranks r1 INNER JOIN ranks r2 ON r1.user_id=r2.user_id WHERE r2.serie_id=#{@serie.id} GROUP BY r1.serie_id ORDER BY similarity DESC, SUM(r1.score) DESC) r ON r.serie_id=s.id WHERE s.id!=#{@serie.id} LIMIT 4")
    # rubocop:enable Layout/LineLength
    # @ranks = @serie.ranks.where(:ranking_id => [1, 2, 3, 4]).order("ranking_id DESC, rank")
    ranking_ids = Ranking.where('is_registerable IS NULL OR is_registerable = FALSE')
    @ranks = @serie.ranks.where(ranking_id: ranking_ids).order(ranking_id: :desc, rank: :asc)

    unless @serie.topic
      topic = Topic.new
      topic.save!
      @serie.topic = topic
      @serie.save!
    end

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render xml: @serie }
    end
  end
end

app/helpers/series_helper.rb
module SeriesHelper
  def serie_image_path(serie, size = :medium)
    rtn = nil

    serie.books.each do |book|
      rtn = book.smallimgurl if size == :small
      rtn = book.mediumimgurl if size == :medium
      rtn = book.largeimgurl if size == :large
      break if rtn
    end
    unless rtn
      rtn = 'nil_small.jpg' if size == :small
      rtn = 'nil_medium.jpg' if size == :medium
      rtn = 'nil_large.jpg' if size == :large
    end

    rtn
  end
end

app/views/series/index.html.haml
= link_to '検索しても出てこない雑誌に掲載された読み切りや・Web漫画などの新しい漫画シリーズを作成する', new_member_serie_path if current_user
= paginate @series
- @series.each do |serie|
  %p.serie
    = link_to image_tag(serie_image_path(serie), :alt=> serie.name, :style => "float: left;"), serie, {:target => "_blank"}
  %p.serie_detail
  %h2= link_to serie.name, serie, {:target => "_blank"}
  .serie_books
    - serie.books.each do |book|
      = link_to book.name, member_book_path(book)
      %br
    %br{:style => "clear: both;"}
= paginate @series
= link_to '検索しても出てこない雑誌に掲載された読み切りや・Web漫画などの新しい漫画シリーズを作成する', new_member_serie_path if current_user

app/views/series/ranking.html.haml
- count = 0
- @series.each do |serie|
  - if current_user && serie.ranks.where(:ranking_id => 1).map{|r| r.user_id}.include?(current_user.id)
    %p.serie{:style => "background-color: cyan;"}
  - else
    %p.serie
  = "順位: #{(r = serie.ranks.where(:ranking_id => 3).first).rank}　得点（重複修正）: #{r.score}　重複数: #{serie.ranks.where(:ranking_id => 1).count}　糞修正順位: #{(r = serie.ranks.where(:ranking_id => 4).first).rank}　糞修正得点: #{r.score}"
  %br/
  = link_to image_tag(serie_image_path(serie), :alt=> serie.name, :style => "float: left;"), serie, {:target => "_blank"} if (count += 1) <= 30
  %p.serie_detail
  %h2= link_to serie.name, serie, {:target => "_blank"}
  = serie.authors.map{|a| a.name}
  = serie.magazines.select("DISTINCT *").map{|m| m.name}
  %br/
  - serie.ranks.where(:ranking_id => [1,2]).sort{|a, b| (a.ranking_id <=> b.ranking_id).nonzero? || a.rank <=> b.rank}.each do |r|
    = link_to "#{r.user.name} (#{r.ranking_id == 2 ? "糞" : nil}#{r.rank}位)", user_path(r.user.name)
  %br{:style => "clear: both;"}/
- end if @series
= paginate @series

app/views/series/ranking_now.csv.haml
順位,合計得点,糞補正後得点,ランキング重複数,糞重複数,コメント数,serie_id,name,漫画家,雑誌,ranks
- @series.each do |serie|
  = "#{serie.rank_info[:rank]},#{serie.rank_info[:sum_of_mark]},#{serie.rank_info[:sum_of_mark_with_kuso]},#{serie.rank_info[:count_rank]},#{serie.rank_info[:count_kuso]},#{serie.rank_info[:count_post]},#{serie.id},#{serie.name},#{serie.authors.map{|a| a.name}.join("　")},#{serie.magazines.map{|m| m.name}.uniq.join("　")},#{serie.ranks.where(:ranking_id => @ranking_ids).sort{|a, b| (a.ranking_id <=> b.ranking_id).nonzero? || a.rank <=> b.rank}.map{|r| "#{r.user.name} (#{r.ranking_id == @ranking_ids.last ? "糞" : nil}#{r.rank}位)"}.join("　")}"

app/views/series/ranking_now.html.haml
= link_to "会誌編集用にランキングとコメント一覧をXMLでダウンロードする", "#{request.url}.xml", download: true
= paginate @series
- @series.each do |serie|
  - if current_user && serie.ranks.where(:ranking_id => @ranking_ids).map{|r| r.user_id}.include?(current_user.id)
    - if @is_should_comment_term && serie.rank_info[:rank] <= 50 && serie.posts.where(:user_id => current_user.id).count == 0
      %p.serie{:style => "background-color: red;"}
        コメントがまだです
    - else
      %p.serie{:style => "background-color: cyan;"}
        ランキングへ入れています
  %p.serie
    順位:
    = serie.rank_info[:rank]
    合計得点:
    = serie.rank_info[:sum_of_mark]
    糞修正後得点:
    = serie.rank_info[:sum_of_mark_with_kuso]
    ランキング重複数:
    = serie.rank_info[:count_rank]
    糞重複数:
    = serie.rank_info[:count_kuso]
    コメント数:
    = serie.rank_info[:count_post]
  = link_to image_tag(serie_image_path(serie), :alt=> serie.name, :style => "float: left;"), serie, {:target => "_blank"} if serie.rank_info[:rank] <= 30
  %p.serie_detail
    %h2= link_to serie.name, serie, {:target => "_blank"}
    = serie.authors.map{|a| a.name}
    = serie.magazines.select("DISTINCT *").map{|m| m.name}
    %br/
    - serie.ranks.where(:ranking_id => @ranking_ids).sort{|a, b| (a.ranking_id <=> b.ranking_id).nonzero? || a.rank <=> b.rank}.each do |r|
      - user = r.user
      - if @is_should_comment_term && current_user && serie.rank_info[:rank] <= 50 && serie.posts.where(:user_id => user.id).count == 0
        %span{:style => "background-color: red;"}>< 未コメ
      = link_to "#{user.name} (#{r.ranking_id == @ranking_ids.last ? "糞" : nil}#{r.rank}位)", user_path(user.name)
      = "　"
  %br{:style => "clear: both;"}/
  %br/
- end if @series
= paginate @series

app/views/series/ranking_now.xml.haml
!!! XML
%series
  - @series.each do |serie|
    %serie
      %rank= "#{serie.rank_info[:rank]}位"
      %name= serie.name
      %authors= serie.authors.map{|a| a.name}.join("・")
      %ranking= "（#{serie.rank_info[:sum_of_mark]}点： 得票数#{serie.rank_info[:count_rank]}, クソ修正後得点#{serie.rank_info[:sum_of_mark_with_kuso]}点, クソ得票数#{serie.rank_info[:count_kuso]}）"
      %magazine= serie.magazines_series.map{|ms| ms.magazine ? (ms.magazine.name + (ms.placed ? (ms.placed != "" ? "（#{ms.placed}）" : "") : "")) : nil}.compact.uniq.join("　")
      %detail
        %content= raw serie.post.content.gsub(/[\r\n]/, "") if serie.post
        %by= serie.post.user.name if serie.post
      - if serie.topic
        %comments= raw (serie.topic.posts - [serie.post]).map{|post| "#{post.content.gsub(/[\r\n]/, "")}【#{post.user.name}#{(rank = serie.ranks.where(ranking_id: @ranking_ids, user_id: post.user.id).first) ? ":#{rank.ranking_id == @ranking_ids[0] ? nil : "糞"}#{rank.rank}位" : nil}】"}.join("\n")

app/views/series/show.html.haml
.serie_image
  = link_to image_tag(serie_image_path(@serie, :large), :alt => @serie.name), serie_to_amazon_url(@serie), {:target => "_blank", :title=>"Amazonで購入"}
.serie_detail
  %h1= @serie.name
  %p.serie_authors
    %h3 著者
    = @serie.authors.map{|a| a.name} if @serie.authors
  %p.serie_magazines
    %h3 掲載誌
    %table
      %tr
        %th 雑誌名
        %th 雑誌掲載情報
        %th 出版社
      - @serie.magazines_series.each do |ms|
        %tr
          %td= ms.magazine && ms.magazine.name
          %td= ms.placed
          %td= ms.magazine && ms.magazine.publisher
  %p.serie_post
    %h3 細部
    = render :partial => "member/topics/post", :locals => {:post => @serie.post} if @serie.post
  - if current_user
    = link_to 'ランキング登録・シリーズ情報修正', edit_member_serie_path(@serie), :class => :serie_edit
%h3 ランキング情報
.serie_ranks
  - @ranks.each do |rank|
    = rank.ranking.name
    = rank.rank
    位
    \#{rank.score}点
    \#{link_to rank.user.name, user_path(rank.user.name) if rank.user}
    %br
= render :partial => "member/topics/topic", :locals => {:topic => @serie.topic, :i => nil}
.serie_similar
  %b 似ている漫画（デモ）
  停止中
  %br
  -# - @similar_series.each do |serie|
    = link_to image_tag(serie_image_path(serie, :small), :alt => serie.name), serie
    = link_to serie.name, serie
    %br
.serie_books
  %b 書籍収録情報
  - @serie.books.each do |book|
    %div
      = link_to image_tag(book.smallimgurl ||  'nil_small.jpg', :alt => book.name), member_book_path(book)
      = link_to book.name, member_book_path(book)